Added 'private config'

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,15 +4,14 @@ cd ~
 
 for prog in bash input gdb irb vim zsh git ycm; do
     echo Installing rc files for ${prog}
-    for file in ~/public-config/${prog}*; do
+    for file in ~/public-config/${prog}* ~/private-config/${prog}*; do
         if [[ -d ${file} ]]; then continue; fi
-        basename=$(basename ${file})
-        if [[ -h ${basename} ]]; then rm ${basename}; fi
-        if [[ -e ${basename} ]]; then
-            echo "ERROR: Can't overwrite non-symlink file: ${basename}" >&2
+        rcname=".$(basename ${file})"
+        if [[ -h ${rcname} ]]; then rm ${rcname}; fi
+        if [[ -e ${rcname} ]]; then
+            echo "ERROR: Can't overwrite non-symlink file: ${rcname}" >&2
         else
-            ln -s ${file}
-            mv {,.}${basename}
+            ln -s ${file} ${rcname}
         fi
     done
 done
