gvim/nvim stuff

diff --git a/OS_specific/Windows/wsl_edit b/OS_specific/Windows/wsl_edit
--- a/OS_specific/Windows/wsl_edit
+++ b/OS_specific/Windows/wsl_edit
@@ -10,9 +10,16 @@
 
 # XXX These paths need to be generated by `./install --tools`.
 # This should provide an option for choosing between vim and nvim as well.
-HOST_PATH='C:\Users\Kyle.Strand\scoop\shims\nvim-qt.exe'
-WSL_PATH='/mnt/c/Users/Kyle.Strand/scoop/shims/nvim-qt.exe'
+# HOST_PATH='C:\tools\neovim\Neovim\bin\nvim-qt.exe'
+# WSL_PATH='/mnt/c/tools/neovim/Neovim/bin/nvim-qt.exe'
+# As long as the `exe` is on the path, this should work.
+HOST_PATH=nvim-qt.exe
+WSL_PATH=nvim-qt.exe
 
+# if [[ ! -x "$WSL_PATH" ]]; then
+#     echo "Cannot find application: '$WSL_PATH'" >&2
+#     exit 1
+# fi
 
 if [[ "$@" == *"--nofork"* ]]; then
     # TODO: this fails with nvim! gvim.exe ignores --nofork, but nvim-qt.exe does NOT.
@@ -28,5 +35,6 @@ else
     fi
 
     # Powershell does not have the same bug as cmd.exe.
-    powershell.exe start -windowstyle hidden '"'$HOST_PATH'"' $ps_argstring
+    # If launching a batch or powershell file instead of an exe, use `-windowstyle hidden`
+    powershell.exe start "$HOST_PATH" $ps_argstring
 fi
